### ISSUE TITLE
layer.homes.format add more crew placeholders.

### ISSUE THREAD

**Issue by FrozenBeard** [RoinujNosde/Dynmap-SimpleClans#2]
Requesting, can we please get more crew placeholders for the formatting of the crew homes shwoing when you hover over, some crews do not set names just their tag, so when you hover over some they just show (home) and nothing else, I would like to at the least display their tag aswell so that we know whos home it is.
other helpful tags could include member count etc.

**Comment by RoinujNosde** [comment]
Clan tag, member count. What else?

**Comment by FrozenBeard** [comment]
Allies and Rivals, their leaders, Bank balance, KDR, Status (verified), Members total/Online.

Basically most things from /crew profile haha, then we can pick and choose as we need them.
