### ISSUE TITLE
I removed Dynmap-Simpleclans but its now hiding all my players?

### ISSUE THREAD

**Issue by FrozenBeard** [RoinujNosde/Dynmap-SimpleClans#5]
I removed the plugin fully to re-gain my map back to normal, but its somehow changed my map settings? How can I fix what Dynmap-Simpleclans has changed, It now permanently hides all players unless a brand new player joins the server for the first time.

**Comment by RoinujNosde** [comment]
Dynmap is probably saving the players visibility status. But I will release the implementation of #3 today.

**Comment by FrozenBeard** [comment]
good shout! I looked and the "hiddenplayers.txt" was populated with 855 people, blimey thats a lot of people online in the day or so i've had this plugn on haha! Ill remove everyone from this file and /dynmap reload. See if that fixes it, thanks!
