### ISSUE TITLE
Error When Enabling Dynmap SimpleClans

### ISSUE THREAD

**Issue by liversnaprocks** [RoinujNosde/Dynmap-SimpleClans#8]
ERROR Error occurred while enabling Dynmap-SimpleClans v1.3.0 (Is it up to date?)
23.09 23:46:28 [Server] INFO java.lang.NullPointerException: null
23.09 23:46:28 [Server] INFO at net.sacredlabyrinth.phaed.dynmap.simpleclans.layers.ClanHomes.initIcons(ClanHomes.java:95) ~[?:?]
23.09 23:46:28 [Server] INFO at net.sacredlabyrinth.phaed.dynmap.simpleclans.layers.ClanHomes.<init>(ClanHomes.java:51) ~[?:?]
23.09 23:46:28 [Server] INFO at net.sacredlabyrinth.phaed.dynmap.simpleclans.DynmapSimpleClans.activate(DynmapSimpleClans.java:67) ~[?:?]
23.09 23:46:28 [Server] INFO at net.sacredlabyrinth.phaed.dynmap.simpleclans.DynmapSimpleClans.onEnable(DynmapSimpleClans.java:47) ~[?:?]
23.09 23:46:28 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-194]
23.09 23:46:28 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-194]
23.09 23:46:28 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-194]
23.09 23:46:28 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-194]
23.09 23:46:28 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-194]
23.09 23:46:28 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-194]
23.09 23:46:28 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-194]
23.09 23:46:28 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870) ~[patched_1.14.4.jar:git-Paper-194]

**Comment by liversnaprocks** [comment]
Thank you! Worked perfectly!

**Comment by RoinujNosde** [comment]
You're welcome!
(I'm going to leave this open, because I'm still fixing it)
